config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'properties#index'
  resources :properties, except: [:new, :create, :delete, :edit] 

  get '/sales/:id/compare', to: 'sales#compare', as: 'compare'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    validates :number, presence: true, uniqueness: true
    validates :full_address, presence: true
    validates :square_feet, presence: true
    validates :lanai, presence: true
    validates :floors, presence: true
    validates :frontage, presence: true
    validates :view, presence: true  

    has_many :sales
    
    def self.sort_by (sort_column)
        Property.order("#{sort_column} asc")
    end
end

app/models/sale.rb
class Sale < ApplicationRecord
    validates :mls, presence: true, uniqueness: true

    belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
require 'pry'

class PropertiesController < ApplicationController
    def index
        @sort_field = params[:sort] ? params[:sort] : "number"
        @properties = Property.sort_by(@sort_field)
    end

    def show
        @property = Property.find_by(:id => params[:id])
        @propSales = @property.sales
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

    def compare
        @sale = Sale.find_by(:id => params[:id])
        @start_date = @sale.sold_date - 180;
        @end_date = @sale.sold_date + 180;
        # retrieve from sales
        @comp_sales = Sale.where("sold_date >= ? AND sold_date <= ?", @start_date, @end_date).all 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # property index sort helpers
    def sort_select_tag (sort_field)
        fields= [{value: '', display: 'Choose Sort Field'}, 
                 {value: 'number', display: 'Number'},
                 {value: 'frontage', display: 'Frontage'}, 
                 {value: 'floors', display: 'Floors'}, 
                 {value: 'square_feet', display: 'Square Feet'}]

        html = "<select name='sort' id='sort'>"
        fields.each do |field|
            html += "<option #{sort_selected_option(field[:value], sort_field)} "
            html += " value=#{field[:value]}>#{field[:display]}</option>"
        end
        html.html_safe
    end

    def sort_selected_option(field, sort_field)
        field==sort_field ? "selected='selected'" : ""
    end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Propcomp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar">
      <h4 class="logo">PropComp</h4>
      <ul class="nav-links">
        <li class="nav-item"><a href=<%= properties_path %>>Properties</a></li>
        <li class="nav-item"><a href="#">About</a></li>
      </ul>
    </nav>

    <div class="container"  role="main">
      <%= yield %>
    </div>

  </body>
</html>

app/views/properties/index.html.erb
<div class="page-container">
    <div id="prop-index-title-container">
        <h1>Property List</h1>
        <%= form_tag properties_path, method: "get" do %> 
            <%= sort_select_tag(@sort_field) %>
            <%= submit_tag "Sort" %>
        <% end %>
    </div>
    <div>
        <table id="properties">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Number</th>
                    <th scope="col">Frontage</th>
                    <th scope="col">Floors</th>
                    <th scope="col">Square Feet</th>
                    <th scope="col">Lanai</th>
                    <th scope="col">View</th>
                </tr>
            </thead>
            <tbody>
                <% @properties.each do | property | %>
                    <tr>
                        <td><%= link_to "View", property_path(property.id) %></td>
                        <td><%= property.number %></td>
                        <td class="align-left"><%= property.frontage %></td>
                        <td><%= property.floors %></td>
                        <td><%= property.square_feet %></td>       
                        <td><%= property.lanai %></td>
                        <td class="align-left"><%= property.view %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>


app/views/properties/show.html.erb
<div class="page-container">
    <h2><%= @property.full_address %></h2>
    <div id="property-details">
        <p>Square Feet: <%= @property.square_feet %></p>
        <p>Lanai: <%= @property.lanai %></p>
        <p>Floors: <%= @property.floors %></p>
        <p>Frontage: <%= @property.frontage %></p>
        <p>View: <%= @property.view %></p>
    </div>
    <h3>Sale Listings</h3>
    <table>
        <tr>
            <th></th>
            <th scope="col">MLS</th>
            <th scope="col">Status</th>
            <th scope="col">Condition</th>
            <th scope="col">Sold Date</th>
            <th scope="col">Sold Price</th>
        </tr>
        <% @propSales.each do | sale | %>
            <tr>
                <% if sale.sold_date then %>
                    <td><%= link_to "Compare", compare_path(sale.id) %></td> 
                <% end %>
                <td class="align-left"><%= sale.mls %></td>
                <td class="align-left"><%= sale.status %></td>
                <td class="align-left"><%= sale.condition %></td>
                <td class="align-left"><%= sale.sold_date %></td>
                <td class="align-left"><%= sale.sold_price %></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/sales/compare.html.erb
<h1>Sales Comparison from <%= @start_date %> to <%= @end_date %>
<h3>Sale Listings</h3>
<table>
    <tr>
        <th scope="col">MLS</th>
        <th scope="col">Number</th>
        <th scope="col">Condition</th>
        <th scope="col">Floors</th>
        <th scope="col">Frontage</th>
        <th scope="col">Sold Date</th>
        <th scope="col">Sold Price</th>
    </tr>
    <% @comp_sales.each do | sale | %>
        <tr>
            <td class="align-left"><%= sale.mls %></td>
            <td class="align-left"><%= sale.number %></td>
            <td class="align-left"><%= sale.condition %></td>
            <td class="align-left"><%= sale.property.floors %></td>
            <td class="align-left"><%= sale.property.frontage %></td>
            <td class="align-left"><%= sale.sold_date %></td>
            <td class="align-left"><%= sale.sold_price %></td>
        </tr>
    <% end %>
</table>


app/views/sales/show.html.erb
<h1>Sales Comparison from <%= @start_date %> to <%= @end_date %>
<h3>Sale Listings</h3>
<table>
    <tr>
        <th scope="col">MLS</th>
        <th scope="col">Number</th>
        <th scope="col">Condition</th>
        <th scope="col">Floors</th>
        <th scope="col">Frontage</th>
        <th scope="col">Sold Date</th>
        <th scope="col">Sold Price</th>
    </tr>
    <% @comp_sales.each do | sale | %>
        <tr>
            <td class="align-left"><%= sale.mls %></td>
            <td class="align-left"><%= sale.number %></td>
            <td class="align-left"><%= sale.condition %></td>
            <td class="align-left"><%= sale.property.floors %></td>
            <td class="align-left"><%= sale.property.frontage %></td>
            <td class="align-left"><%= sale.sold_date %></td>
            <td class="align-left"><%= sale.sold_price %></td>
        </tr>
    <% end %>
</table>
